### PR TITLE
i18n for BaseOccurence model fields

### PR DESCRIPTION
**Pull request by jackill88**
add verbose_name to BaseOccurrence's model fields to help spread this library across non-english countries

### CODE REVIEW

**Comment by gregplaysguitar** [comment]
Hi, thanks for this! I had 3rd-party builds turned off in circleci, but I've turned them on, so if you push to your branch again then they should run. There's currently a linter error - see https://app.circleci.com/pipelines/github/gregplaysguitar/django-eventtools/1/workflows/4c4d65cd-d1b8-4175-bcc8-6611eec1031d/jobs/163

**Comment by jackill88** [comment]
> Hi, thanks for this! I had 3rd-party builds turned off in circleci, but I've turned them on, so if you push to your branch again then they should run. There's currently a linter error - see https://app.circleci.com/pipelines/github/gregplaysguitar/django-eventtools/1/workflows/4c4d65cd-d1b8-4175-bcc8-6611eec1031d/jobs/163

Hi! Should i create new pull request?

**Comment by gregplaysguitar** [comment]
@jackill88 I think if you just push an update to this branch it'll run the tests. But otherwise, another PR would work too

**Comment by gregplaysguitar** [comment]
Addressed in #36

**Pull request closed without merging**
