### PR TITLE
fixed bug: timezones weren't being inserted at all

### PR DESCRIPTION
**Pull request by austing**
I don't know how it is possible, but this wasn't fixing timezone support. There was a bug very early on in the file. A very simple bug. Now it works, so far as I can tell, but obviously the tests didn't cover it.

### CODE REVIEW

**Comment by gregplaysguitar** [comment]
Ok, do you think you could write a test that covers this issue?

**Comment by austing** [comment]
I'll try to do that when I can, in the next couple of days. Hopefully not
in too long.

**Comment by austing** [comment]
An exception was raised while trying to run next_occurrences on an event
subclass that had a repeating occurrence. So I'll just add a test of
exactly that case -- at least to make sure that no exceptions are raised,
if not to check that the output was correct.

**Comment by gregplaysguitar** [comment]
Cool, thanks.

**Comment by gregplaysguitar** [comment]
Actually, it turns out the settings weren't being run with timezone active at all, or this bug would have been caught. I'll update the test suite

**Pull request closed without merging**
